### ISSUE TITLE
Body text links linking to staging site

### ISSUE THREAD

**Issue by cmontwill** [Threespot/aldf-wp#220]
@tedw It looks like most/all of the in body text links are linking to the staging site. 

Click on the 'ALDF annual rankings' link in the body of this page: [https://aldf.org/focus_area/companion-animals/](https://aldf.org/focus_area/companion-animals/)
![screen shot 2018-07-16 at 11 36 12 am](https://user-images.githubusercontent.com/5890745/42768040-77f9aeda-88ec-11e8-9c26-15c694d8a522.png)

I think we said all these would be changed during the flip, is this something still in progress or an issue? 

Chris

**Comment by tedw** [comment]
Correct, ALDF needs to use the link button in the wysiwyg editor instead of pasting the link manually. This will ensure the URL never breaks, regardless of if the slug changes or which environment we’re on.

**Comment by cmontwill** [comment]
Correct, I think LC said we were going to run a script to change any that might be like this. However, it looks like they did this wrong across the site. Is there any automated way to deal with this?

**Comment by tedw** [comment]
Not that I’m aware of but can look into it.

We may be able to automatically replace `live-aldf-wp.pantheonsite.io` with `aldf.org` but this would not prevent the link from breaking if the permalink ever changed.

**Comment by cmontwill** [comment]
@tedw gotcha. Can you let me know if that is possible? It might have to be a stop gap.

**Comment by tedw** [comment]
Actually, this should be resolved when I setup the redirects to force HTTPS. THat should also redirect any `live-aldf-wp.pantheonsite.io` URLs to `aldf.org`.

**Comment by cmontwill** [comment]
@tedw cool, when is that going to happen?

**Comment by tedw** [comment]
I'm already working on it, give me 15 min

**Comment by tedw** [comment]
Redirect has been deployed

**Comment by lizzycederberg** [comment]
How long do we need to wait? I'm currently still seeing them point to the Pantheon URL

**Comment by tedw** [comment]
Hmm, it worked for me right away.
